name: Deploy to EC2

on:
  push:
    branches:
      - main # This can be replaced with your deployment branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: DEV
    env:
      PORT: 3000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: 18.212.109.146
          username: ubuntu
          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEogIBAAKCAQEAm81zHsLoVinMSMgWaVBj33FSROCN6s34OBC08FGFUEqA3RKC
            04lzTEsIa6GjfsUA/nuzB8tCpeZm+slzG9VpnCCmHc4oYp5OraU35NKd1FcBKIhl
            F/UoO18eXqV4IX6/GfMIwSpi6J7lN0EU4ElikKJ4CtYhWufG3liBt0CdP6Sk1YSH
            6fJytT58HkMBo7oK/HXu4fHU++7rxuWVNhFcAqlVt0bDdvQY00+ECAE6IfESpuDX
            mVfVgC92ljGeIo/yJkc4IHOEtKi5CRQeYzir0ZgwCCmenI0PuC7bIsYCNNTtzySg
            honu9e72791VGU2uHrQsWPkhIumuqOQ67QeB3QIDAQABAoIBABCl/IYt95u1bbHd
            R5/LSlDHEC5x/Fg52CtNhbgkTeWNgIWfA8HM7zgY0HaH2Cukq32GBFRx4NZPb3Oe
            8SDpRha72mRW8jPPjMK7Y+ScqObWwTXulTbhKIJnoJwmfFa/73W7ZZUWjWkkCYRE
            /REWZmTkJ4Wo6fmHyNVbicjmK6dwKcdlD5FvuKX9lX/A8wWubK3Knik0Vl1cEMyj
            pxqcyHejIw6lktWwl5jHAYLEtWjMFLV1Ir2x9xy8xIrweriTYaUGawrpie8sKN5L
            9Hp/rnuQSGAfrDzflHk3A+aaBVdGX39YVxxDpRpylQMH8XZNgVFm5IJSwY87pYFL
            9klxk8ECgYEA+DF97zJfgJml8olZR/jphLqydQLY+28LkGW5qMqecdk5unwLJBdm
            ehHS2XfphqptgJ1/bMagXd/N0ZSR27FZf1Dq/JgXBQuDZgYU8Day3uNOwgttAe7U
            HRpQ0gqw/PeZ+7siNGtAXcj3WP9csG0uIf/M108iFNBwkui4k/Qq/y0CgYEAoLQB
            qbKEy6ljHI9gbhVbtzJ48Ms6pKDxBeLtkZsDFnO7UxQFpg2nFsqamEsROWOAAYxw
            SchrLrVnxpNC65odZlpiaHKW4kMdf/VnjicbRxdY99L9ApN7aWTSjYNW7r8fktxX
            ScI1vY0MG6HfahCBrUe6jfwDI3+4uZm7u9Sju3ECgYBIk1BcDcLXfBaGoZs17Jd8
            dIuSo86HV6VuCBEORpGmgPrciUFIwH762xNo/COReWyj22pTiJGEYdlxm5w7PdUJ
             4cOVMXQpyYAW6VheFeCgRJ/XJjguBISKLhPMF8xBbLXeYo5R/brIseeCYsnb3VFM
            J9ziaQVySLFihCLVQOUB0QKBgDJOBtM7KayjGn5fN11eXDZtm0QtKe9M3gXssldJ
            Ad9uXO41r0r6rRpKU7hmjz66seBKOQAvt7WIXbLgeCtOM/PNSU7OyAKN5dcfV8o8
            3aIUYeo55q9+wTwNrodT3Muhkl2jkcNqAu6SD3863bfS8PTwJiq5/7WGDqoywHyc
            pKBRAoGAAS9DQCzv+KeyYPyZA+RGFm/E1ZFtfmsJsRlROD4YMahU1yKc/cz+OYAC
            Z9Ba7eOePmQ47w94XvyPOxTU8vkOKDZY6k+TjyCShnDQuN64nPuHb9tdRQDt4lCx
            P8irLLP5ns2qQvq/SWyQsiTXhnQJoyef2zQ/bjkS1e3+Hk7hdG0=
            -----END RSA PRIVATE KEY-----
          script: |
            cd ~/seyi-api # replace this with your actual project directory path
            git pull origin main
            npm install
            pm2 stop index.js
            pm2 start index.js 
